// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLfqwvaBo_SI8PSUkm6HQUuNbSJwHbo5Q',
    appId: '1:777104655780:web:106997caad7d77e185ed31',
    messagingSenderId: '777104655780',
    projectId: 'clubx-d21f0',
    authDomain: 'clubx-d21f0.firebaseapp.com',
    storageBucket: 'clubx-d21f0.firebasestorage.app',
    measurementId: 'G-7JV3QLR7XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZehfliZTvnQ4OuObNTsEqT-k980PXpa0',
    appId: '1:777104655780:android:22b84024350b93e985ed31',
    messagingSenderId: '777104655780',
    projectId: 'clubx-d21f0',
    storageBucket: 'clubx-d21f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsauceQ8BloCEvR0t14JqP6cKv3ZnrEuM',
    appId: '1:777104655780:ios:fc4ad6f9a89a9abf85ed31',
    messagingSenderId: '777104655780',
    projectId: 'clubx-d21f0',
    storageBucket: 'clubx-d21f0.firebasestorage.app',
    iosBundleId: 'com.example.clubx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsauceQ8BloCEvR0t14JqP6cKv3ZnrEuM',
    appId: '1:777104655780:ios:fc4ad6f9a89a9abf85ed31',
    messagingSenderId: '777104655780',
    projectId: 'clubx-d21f0',
    storageBucket: 'clubx-d21f0.firebasestorage.app',
    iosBundleId: 'com.example.clubx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLfqwvaBo_SI8PSUkm6HQUuNbSJwHbo5Q',
    appId: '1:777104655780:web:c369e87739ee130385ed31',
    messagingSenderId: '777104655780',
    projectId: 'clubx-d21f0',
    authDomain: 'clubx-d21f0.firebaseapp.com',
    storageBucket: 'clubx-d21f0.firebasestorage.app',
    measurementId: 'G-X8S6QB2NB3',
  );
}
